export const categories = [
  { name: "Авто из Америки" },
  { name: "Авто из Европы" },
  { name: "Авто из Китая" },
  { name: "Авто из России" },
];

export const carBrands = [
  { name: "BMW" },
  { name: "Volvo" },
  { name: "Audi" },
  { name: "Mercedes-Benz" },
  { name: "Honda" },
  { name: "Toyota" },
  { name: "Nissan" },
  { name: "Mazda" },
  { name: "Opel" },
  { name: "Peugeot" },
  { name: "Volkswagen" },
  { name: "BYD" },
  { name: "GEELY" },
  { name: "XIAOMI" },
  { name: "ZEEKR" },
  { name: "Tesla" },
  { name: "Ferrari" },
  { name: "Lamborghini" },
  { name: "Porsche" },
  { name: "Bugatti" },
  { name: "Rolls-Royce" },
  { name: "Jaguar" },
];

export const products = [
  {
    name: "BMW 5-Series G30",
    yearOfManufacture: 2021,
    price: 26000,
    imageUrl: "/carsData/bmw-5-europ-img.jpg",
    categoryId: 1,
    carBrandId: 1,
  },
  {
    name: "BMW 3-Series G20",
    yearOfManufacture: 2021,
    price: 14000,
    imageUrl: "/carsData/bmw_3_sedan.jpg",
    categoryId: 1,
    carBrandId: 1,
  },
  {
    name: "Volvo XC60",
    yearOfManufacture: 2022,
    price: 18000,
    imageUrl: "/carsData/volvo-xc-60-europe-img.jpg",
    categoryId: 1,
    carBrandId: 2,
  },
  {
    name: "Audi Q8",
    yearOfManufacture: 2022,
    price: 45000,
    imageUrl: "/carsData/audi-q8-europ-img.jpg",
    categoryId: 1,
    carBrandId: 3,
  },
  {
    name: "Audi A6",
    yearOfManufacture: 2022,
    price: 18000,
    imageUrl: "/carsData/audi_a6_sedan.jpg",
    categoryId: 1,
    carBrandId: 3,
  },
  {
    name: "Audi A7",
    yearOfManufacture: 2022,
    price: 31000,
    imageUrl: "/carsData/audi-a7-germany-img.jpg",
    categoryId: 1,
    carBrandId: 3,
  },
  {
    name: "Mercedes-benz GLE",
    yearOfManufacture: 2022,
    price: 42000,
    imageUrl: "/carsData/mercedes-gle-europ-img.jpg",
    categoryId: 2,
    carBrandId: 4,
  },
  {
    name: "Opel Insignia Combi",
    yearOfManufacture: 2021,
    price: 9000,
    imageUrl: "/carsData/opel-insignia-europ-img.jpg",
    categoryId: 2,
    carBrandId: 9,
  },
  {
    name: "Volkswagen Tiguan",
    yearOfManufacture: 2021,
    price: 14500,
    imageUrl: "/carsData/vw-tiguan-img.jpg",
    categoryId: 2,
    carBrandId: 11,
  },
  {
    name: "Peugeot 5008",
    yearOfManufacture: 2021,
    price: 13000,
    imageUrl: "/carsData/peugeot-5008-img.jpg",
    categoryId: 2,
    carBrandId: 10,
  },
  {
    name: "BYD Yuan UP",
    yearOfManufacture: 2024,
    price: 21900,
    imageUrl: "/carsData/IMG_7055.jpg",
    categoryId: 3,
    carBrandId: 12,
  },
  {
    name: "GEELY Geome Star Wish",
    yearOfManufacture: 2024,
    price: 17500,
    imageUrl: "/carsData/Geely_Geometry_f34blue_1b.png",
    categoryId: 3,
    carBrandId: 13,
  },
  {
    name: "XIAOMI SU7",
    yearOfManufacture: 2024,
    price: 31700,
    imageUrl: "/carsData/SU7.jpg",
    categoryId: 3,
    carBrandId: 14,
  },
  {
    name: "ZEEKR 007",
    yearOfManufacture: 2024,
    price: 33000,
    imageUrl: "/carsData/zeekr-007.png",
    categoryId: 3,
    carBrandId: 15,
  },
];
